os: linux
language: go
go: '1.10'
dist: trusty
sudo: required
services:
  - docker
         
before_install:
  docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD";

install:
        - make get ./...

script:
  - go build
  - cd ./server && go build && docker build -t stub .
  - docker tag stub tochka/stub-server:latest
  - docker push tochka/stub-server